env:
  global:
  - TERM=dumb
notifications:
  email: false
git:
  quiet: true
  depth: false
language: node
node_js: lts/*
python: 3.7
os: linux
addons:
  apt:
    packages:
      - curl
      - python3-pip
install: true
before_install:
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master ;
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
    stop_any 80 3000 5000 8080 5432
  - |
    export PATH=$HOME/.local/bin:$PATH
    pip3 install --user --upgrade pip setuptools
    pip install --user --upgrade httpie
jobs:
  include:

  - stage: test
    name: test
    before_script:
      - cd $TRAVIS_BUILD_DIR && npm i -E
      - cd $TRAVIS_BUILD_DIR && npm start
      - cd $TRAVIS_BUILD_DIR && npm run logs &
      - wait_for 8080
    script:
      - http :8080
    after_script:
      - cd $TRAVIS_BUILD_DIR && npm stop

  - stage: deploy
    env:
      - secure: "wwjQFNduLAcRrolylJajmKg6GUWznpk2DdRZt1goLU9dH/bwSJ5VVF+AFIKKtnyxHRXyG0ek2ohjPyUBKXAwBNuHsWH3Bb5PMAyJov25jQopAyAgowM76KhPnMtaEt4/ZU5TnaHkWOMixN+WxgbPzBv4Qwv/7w4jJ5iWOBqk7lBNXufw41OfsXRSemNf0T8Mg96FkOYezHqV+KP96VcglVAks9WEcMpAK5Vl1uk5pf2Fy/i/3ZC70Vrewu+oOHz1hCbHNL5+ASGNSuzkEPKUHjhS2bbTiZOmRVHoqDG7DfPpINMvUMWfwernG8bb1uBiyPs03Tg7w2J0P2uDoO0jfroTh84M3w3KSyhQbd/RMgb79F8n8o6UcE2iZpR32mFCpW1NE1CfZKs8xSjq5QZyaNo0fyVM6+axMyv4mn+Wp9VNBDSBzTHAWh0tZlRUWrdD2S2QOFDAyt6GC2OkyJfXLTEaAeIWr9h2gs4FYcWCenibVQ1vpq0W5d0/wWSBlYgjJqQcbke8l+WQ7B/miKStVYKjplHuICH2HoOEsw+SwBQ8CVZkF2ykHbua+B+0G0/HhZG5GdnXc3GlSys6ZrV9r6YIsa+OMGbpGAPdbTYEox3A9zJcWs1tCezFiGjLxyeI04eddavoXvcI7ltElqQnjgbRyIjhrrlE5xpWdP99pp8="
    name: GitHub pages deployment
    script: skip
    before_deploy:
    - cd $TRAVIS_BUILD_DIR && npm i
    - cd $TRAVIS_BUILD_DIR && npm run gh
    deploy:
      provider: pages
      skip-cleanup: true
      keep-history: true
      target_branch: gh-pages
      github-token: "$GITHUB_TOKEN"
      local-dir: $TRAVIS_BUILD_DIR/dist
      on:
        branch: master

cache:
  npm: true
  packages: true
  directories:
  - ~/.local/daggerok
  - node_modules/
  - ~/.n*
